package vulndb

import (
	"strings"
	"testing"
)

// find sucht ein Paket im Ergebnis. Die Reihenfolge ist sortiert, aber ein
// Test, der über einen Index zugreift, bricht beim ersten neuen Testdatum.
func find(t *testing.T, res LockfileResult, name string) Package {
	t.Helper()
	for _, p := range res.Packages {
		if p.Name == name {
			return p
		}
	}
	t.Fatalf("package %q not in the result (%d packages)", name, len(res.Packages))
	return Package{}
}

// package-lock.json in der heute üblichen Bauform (v3): die flache Karte
// `packages`. Geprüft wird vor allem die Rollenbestimmung — sie ist der Grund,
// warum der Wurzeleintrag überhaupt gelesen wird.
func TestParseNpmLockV3(t *testing.T) {
	raw := []byte(`{
	  "name": "demo",
	  "lockfileVersion": 3,
	  "packages": {
	    "": {"name":"demo","dependencies":{"lodash":"^4.17.0"},"devDependencies":{"jest":"^29.0.0"}},
	    "node_modules/lodash": {"version":"4.17.20"},
	    "node_modules/jest": {"version":"29.7.0","dev":true},
	    "node_modules/loader-utils": {"version":"1.4.0"},
	    "node_modules/jest/node_modules/chalk": {"version":"4.1.2","dev":true},
	    "node_modules/@babel/core": {"version":"7.23.0"},
	    "packages/ui": {"resolved":"packages/ui","link":true}
	  }
	}`)
	res, err := ParseLockfile("frontend/package-lock.json", raw)
	if err != nil {
		t.Fatal(err)
	}
	if res.Ecosystem != EcosystemNPM {
		t.Errorf("ecosystem = %q, want %q", res.Ecosystem, EcosystemNPM)
	}
	// Der Workspace-Symlink ist kein installiertes Paket und darf nicht
	// mitgezählt werden — sonst fragt der Scan nach einer Version, die es in
	// keiner Registry gibt.
	if len(res.Packages) != 5 {
		t.Fatalf("got %d packages, want 5: %+v", len(res.Packages), res.Packages)
	}
	if p := find(t, res, "lodash"); p.Version != "4.17.20" || p.Dependency != depDirect {
		t.Errorf("lodash = %+v, want 4.17.20/direct", p)
	}
	if p := find(t, res, "jest"); p.Dependency != depDev {
		t.Errorf("jest = %+v, want dev", p)
	}
	// Nur im Baum vorhanden, nicht in der Wurzel verlangt → transitiv.
	if p := find(t, res, "loader-utils"); p.Dependency != depTransitive {
		t.Errorf("loader-utils = %+v, want transitive", p)
	}
	// Verschachtelte node_modules: der Name ist das, was hinter dem LETZTEN
	// node_modules/ steht — sonst hieße das Paket "jest/node_modules/chalk".
	if p := find(t, res, "chalk"); p.Version != "4.1.2" {
		t.Errorf("chalk = %+v, want 4.1.2", p)
	}
	if p := find(t, res, "@babel/core"); p.Version != "7.23.0" {
		t.Errorf("@babel/core = %+v", p)
	}
}

// lockfileVersion 1 kennt die flache Karte noch nicht — der Baum wird
// rekursiv gelesen.
func TestParseNpmLockV1(t *testing.T) {
	raw := []byte(`{
	  "lockfileVersion": 1,
	  "dependencies": {
	    "lodash": {"version":"4.17.20"},
	    "webpack": {"version":"4.46.0","dependencies":{"loader-utils":{"version":"1.4.0"}}},
	    "jest": {"version":"26.0.0","dev":true}
	  }
	}`)
	res, err := ParseLockfile("package-lock.json", raw)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Packages) != 4 {
		t.Fatalf("got %d packages, want 4: %+v", len(res.Packages), res.Packages)
	}
	if p := find(t, res, "loader-utils"); p.Version != "1.4.0" {
		t.Errorf("the nested dependency was not found: %+v", p)
	}
	if len(res.Notes) == 0 {
		t.Error("v1 must report that the roles are a guess")
	}
}

func TestParseComposerLock(t *testing.T) {
	raw := []byte(`{
	  "packages": [
	    {"name":"monolog/monolog","version":"2.3.0"},
	    {"name":"guzzlehttp/guzzle","version":"v7.4.0"}
	  ],
	  "packages-dev": [
	    {"name":"phpunit/phpunit","version":"9.5.0"}
	  ]
	}`)
	res, err := ParseLockfile("composer.lock", raw)
	if err != nil {
		t.Fatal(err)
	}
	if res.Ecosystem != EcosystemPackagist {
		t.Errorf("ecosystem = %q", res.Ecosystem)
	}
	// Das führende "v" ist Schreibweise des Tags. Bliebe es stehen, fände OSV
	// das Paket nicht — und der Scan meldete fälschlich „sauber".
	if p := find(t, res, "guzzlehttp/guzzle"); p.Version != "7.4.0" {
		t.Errorf("guzzle = %q, want 7.4.0 (leading v removed)", p.Version)
	}
	if p := find(t, res, "phpunit/phpunit"); p.Dependency != depDev {
		t.Errorf("phpunit = %+v, want dev", p)
	}
}

func TestParsePubspecLock(t *testing.T) {
	raw := []byte(`# Generated by pub
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "abc123"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "0.13.3"
  test:
    dependency: "direct dev"
    source: hosted
    version: "1.24.0"
  my_internal_lib:
    dependency: "direct main"
    description:
      path: "../internal"
    source: path
    version: "0.0.1"
sdks:
  dart: ">=3.0.0 <4.0.0"
`)
	res, err := ParseLockfile("pubspec.lock", raw)
	if err != nil {
		t.Fatal(err)
	}
	if res.Ecosystem != EcosystemPub {
		t.Errorf("ecosystem = %q", res.Ecosystem)
	}
	// Das path-Paket kommt nicht von pub.dev und hat keine Entsprechung in den
	// Datenbanken — es darf nicht mitgezählt, aber auch nicht verschwiegen
	// werden.
	if len(res.Packages) != 3 {
		t.Fatalf("got %d packages, want 3: %+v", len(res.Packages), res.Packages)
	}
	if p := find(t, res, "http"); p.Version != "0.13.3" || p.Dependency != depDirect {
		t.Errorf("http = %+v, want 0.13.3/direct", p)
	}
	if p := find(t, res, "test"); p.Dependency != depDev {
		t.Errorf("test = %+v, want dev — \"direct dev\" is a dev dependency", p)
	}
	if p := find(t, res, "async"); p.Dependency != depTransitive {
		t.Errorf("async = %+v, want transitive", p)
	}
	if len(res.Notes) == 0 || !strings.Contains(res.Notes[0], "skipped") {
		t.Errorf("the skipped path package must be reported: %v", res.Notes)
	}
}

// Nicht unterstützte Lockdateien müssen laut scheitern und den Ausweg nennen —
// ein halb gelesenes Lockfile meldet weniger Pakete als da sind, und das liest
// sich wie eine Entwarnung.
func TestParseLockfileUnsupported(t *testing.T) {
	for _, name := range []string{"yarn.lock", "pnpm-lock.yaml", "Gemfile.lock"} {
		_, err := ParseLockfile(name, []byte("whatever"))
		if err == nil {
			t.Fatalf("%s: expected an error", name)
		}
	}
	_, err := ParseLockfile("yarn.lock", nil)
	if !strings.Contains(err.Error(), "query_batch") {
		t.Errorf("the error must name the way out (query_batch): %v", err)
	}
}
